---
- name: docker configure
  hosts: [server]
  become: true
  tasks:
  - name: apt update
    command: sudo apt update

  - name: Install python & pip
    command: sudo apt install -y python-pip
     
  - name: Install Docker
    command: sudo apt-get install -y docker.io
    become: yes
    become_user: root

  - name: start docker service
    command: sudo systemctl start docker
    become: yes
    become_user: root

  - name: run as conatainer
    command: docker run -td -p 8080:8081 snehalatha15/insureimage:1.0    
